version: "3.5"

networks:
  default-network:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: deployment/local/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm
    networks:
      - default-network

  php-fpm:
    build:
      context: .
      dockerfile: deployment/local/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: letters_parser_php_fpm
    networks:
      - default-network

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DOCKER_DB_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - default-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8090:80"
    networks:
      - default-network
